"""Problem snipping prototype for extracting question spans from PDFs.

This module follows the roadmap in ``docs/problem_extraction_plan_en.md`` by
building a lightweight extractor that can:

* scan a PDF in reading order and detect question anchors
* assemble question spans along with their bounding boxes
* generate an annotated PDF that visually marks each detected question
* emit structured metadata for downstream (Gemini) consumers later on

The implementation intentionally keeps the data model small but compatible with
future expansions (column detection, QID generation, etc.).
"""

from __future__ import annotations

import json
import itertools
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple, TYPE_CHECKING

import fitz  # PyMuPDF

RectTuple = Tuple[float, float, float, float]

if TYPE_CHECKING:  # pragma: no cover - typing only
    from storage_manager import StorageManager


@dataclass
class TextLine:
    """Represents a normalized line of text extracted from the PDF."""

    page_index: int
    text: str
    bbox: RectTuple
    block_id: int


@dataclass
class ProblemSegment:
    """Detected problem/question segment with metadata useful for marking."""

    index: int
    display_number: str
    text: str
    options: List[str]
    page_spans: Dict[int, List[RectTuple]]
    anchor_pattern: str
    metadata: Dict[str, str] = field(default_factory=dict)


@dataclass
class ExtractionArtifacts:
    """Filesystem artifacts generated by :class:`ProblemSnipper`."""

    segments: List[ProblemSegment]
    annotated_pdf: Optional[Path]
    metadata_json: Optional[Path]


@dataclass
class _AnchorPattern:
    """Internal helper that holds compiled regex patterns for anchors."""

    name: str
    regex: re.Pattern


@dataclass
class _ProblemBuilder:
    """Incrementally builds a :class:`ProblemSegment`."""

    index: int
    display_number: str
    anchor_pattern: str
    lines: List[TextLine] = field(default_factory=list)
    options: List[str] = field(default_factory=list)
    max_option_index: int = 0
    metadata: Dict[str, str] = field(default_factory=dict)

    def add_line(
        self,
        line: TextLine,
        *,
        is_anchor_line: bool = False,
        is_option: bool = False,
        option_index: Optional[int] = None,
        append_last_option: bool = False,
    ) -> None:
        self.lines.append(line)
        if is_anchor_line:
            return
        if is_option:
            self.options.append(line.text)
            if option_index is not None and option_index > self.max_option_index:
                self.max_option_index = option_index
        elif append_last_option and self.options:
            stripped = line.text.strip()
            if stripped and not re.match(r"^(정답|해설|답)\b", stripped):
                self.options[-1] = f"{self.options[-1]}\n{line.text}"

    def to_segment(self) -> ProblemSegment:
        text = "\n".join(line.text for line in self.lines)
        page_spans: Dict[int, List[RectTuple]] = {}
        for line in self.lines:
            page_spans.setdefault(line.page_index, []).append(line.bbox)
        return ProblemSegment(
            index=self.index,
            display_number=self.display_number,
            text=text,
            options=list(self.options),
            page_spans=page_spans,
            anchor_pattern=self.anchor_pattern,
            metadata=dict(self.metadata),
        )


class ProblemSnipper:
    """Lightweight PDF question extractor with basic marking support."""

    def __init__(self) -> None:
        self.anchor_patterns: List[_AnchorPattern] = [
            _AnchorPattern("korean_parenthesis", re.compile(r"^\s*(?:문제\s*)?\(?(?P<num>\d+)\)?[.)]\s+")),
            _AnchorPattern("korean_bun", re.compile(r"^\s*(?P<num>\d+)\s*번\s+")),
            _AnchorPattern("bracketed", re.compile(r"^\s*\[(?P<num>\d+)\]\s+")),
            _AnchorPattern("english_q", re.compile(r"^\s*Q\.?\s*(?P<num>\d+)\s*")),
            _AnchorPattern("english_question", re.compile(r"^\s*Question\s+(?P<num>\d+)\s*")),
            _AnchorPattern("numeric_period", re.compile(r"^\s*(?P<num>\d+)\.[\s\S]*")),
        ]
        self.option_patterns: List[re.Pattern] = [
            re.compile(r"^\s*[①-⑳]"),
            re.compile(r"^\s*\(?[0-9]{1,2}\)?[).]\s+"),
            re.compile(r"^\s*[A-F][).]\s+"),
        ]
        self._year_pattern = re.compile(r"^\s*(?:19|20)\d{2}(?:\s*(?:년|년도))?\s*$")
        self._author_pattern = re.compile(r"^\s*출제자\s*[:：]", re.IGNORECASE)
        # Palette intentionally limited for clarity when highlighting.
        self.highlight_palette: Sequence[Tuple[float, float, float]] = (
            (0.95, 0.60, 0.08),  # amber
            (0.20, 0.60, 0.86),  # blue
            (0.44, 0.74, 0.27),  # green
            (0.85, 0.33, 0.31),  # red
            (0.55, 0.35, 0.64),  # purple
        )
        self._last_anchor_name: str = "unknown"
        self._last_anchor_delimiter: Optional[str] = None
        self._last_anchor_number: Optional[int] = None
        self._circled_digit_map: Dict[str, int] = {
            "①": 1,
            "②": 2,
            "③": 3,
            "④": 4,
            "⑤": 5,
            "⑥": 6,
            "⑦": 7,
            "⑧": 8,
            "⑨": 9,
            "⑩": 10,
            "⑪": 11,
            "⑫": 12,
            "⑬": 13,
            "⑭": 14,
            "⑮": 15,
            "⑯": 16,
            "⑰": 17,
            "⑱": 18,
            "⑲": 19,
            "⑳": 20,
        }
        self._pending_year_marker: Optional[str] = None

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def extract(self, pdf_path: Path | str, *, assign_qids: bool = True) -> List[ProblemSegment]:
        """Extract problem segments from ``pdf_path`` in reading order."""

        source = Path(pdf_path)
        if not source.exists():
            raise FileNotFoundError(f"PDF not found: {source}")

        doc = fitz.open(source)
        try:
            lines = self._collect_lines(doc)
            segments = self._assemble_segments(lines)
        finally:
            doc.close()
        if assign_qids:
            try:
                from pdf_processor.utils.qid import compute_file_fingerprint, make_segment_qid

                fingerprint = compute_file_fingerprint(source)
                for segment in segments:
                    qid = make_segment_qid(fingerprint, segment)
                    segment.metadata.setdefault("qid", qid)
            except Exception:
                # Fail silently: QIDs are optional, but loggable via higher-level callers.
                pass
        # Ensure primary page / question metadata is available for downstream matchers.
        for segment in segments:
            try:
                primary_page = min(segment.page_spans.keys()) if segment.page_spans else 0
            except Exception:
                primary_page = 0
            segment.metadata.setdefault("page", primary_page + 1)
            segment.metadata.setdefault("question_number", segment.display_number)
        return segments

    @staticmethod
    def serialize_segment(segment: ProblemSegment) -> Dict[str, Any]:
        """Return a JSON-serializable representation of ``segment``."""

        return {
            "index": segment.index,
            "display_number": segment.display_number,
            "text": segment.text,
            "options": list(segment.options),
            "page_spans": {
                int(page): [list(rect) for rect in rects]
                for page, rects in segment.page_spans.items()
            },
            "anchor_pattern": segment.anchor_pattern,
            "metadata": dict(segment.metadata),
        }

    @classmethod
    def serialize_segments(cls, segments: Sequence[ProblemSegment]) -> List[Dict[str, Any]]:
        return [cls.serialize_segment(segment) for segment in segments]

    def store_segments(
        self,
        storage_manager: "StorageManager",
        job_id: str,
        segments: Sequence[ProblemSegment],
    ) -> str:
        """Persist ``segments`` using the shared ``StorageManager`` helper."""

        serializable = self.serialize_segments(segments)
        return storage_manager.store_problem_segments(job_id, serializable)

    def write_outputs(
        self,
        pdf_path: Path | str,
        segments: Sequence[ProblemSegment],
        output_dir: Optional[Path | str] = None,
        annotate: bool = True,
        dump_json: bool = True,
    ) -> ExtractionArtifacts:
        """Persist annotated PDF + metadata JSON; return created artifacts."""

        source = Path(pdf_path)
        if output_dir is None:
            output_dir = Path("output") / "problem_snips"
        out_dir = Path(output_dir)
        out_dir.mkdir(parents=True, exist_ok=True)

        annotated_pdf = None
        metadata_json = None

        if annotate and segments:
            annotated_pdf = out_dir / f"{source.stem}_annotated.pdf"
            self._write_annotated_pdf(source, annotated_pdf, segments)

        if dump_json:
            metadata_json = out_dir / f"{source.stem}_segments.json"
            self._write_metadata_json(metadata_json, segments)

        return ExtractionArtifacts(list(segments), annotated_pdf, metadata_json)

    # ------------------------------------------------------------------
    # Core extraction helpers
    # ------------------------------------------------------------------
    def _collect_lines(self, doc: fitz.Document) -> List[TextLine]:
        lines: List[TextLine] = []
        for page_index, page in enumerate(doc):
            page_dict = page.get_text("dict")
            for block_id, block in enumerate(page_dict.get("blocks", [])):
                if block.get("type") != 0:
                    continue
                for line in block.get("lines", []):
                    spans = line.get("spans", [])
                    text = "".join(span.get("text", "") for span in spans).strip()
                    if not text:
                        continue
                    raw_bbox = tuple(float(value) for value in line.get("bbox", []))
                    if len(raw_bbox) != 4:
                        continue
                    bbox: RectTuple = (
                        raw_bbox[0],
                        raw_bbox[1],
                        raw_bbox[2],
                        raw_bbox[3],
                    )
                    lines.append(
                        TextLine(
                            page_index=page_index,
                            text=text,
                            bbox=bbox,
                            block_id=block_id,
                        )
                    )
        return lines

    def _assemble_segments(self, lines: Sequence[TextLine]) -> List[ProblemSegment]:
        segments: List[ProblemSegment] = []
        builder: Optional[_ProblemBuilder] = None
        next_index = 1

        for idx, line in enumerate(lines):
            # Attach metadata marker lines before attempting anchor detection.
            if builder is not None and self._is_author_line(line.text):
                builder.metadata.setdefault("author", line.text.strip())
                continue
            if self._is_year_marker(line.text):
                year_text = line.text.strip()
                if builder is not None and not builder.lines:
                    builder.metadata.setdefault("exam_year", year_text)
                else:
                    self._pending_year_marker = year_text
                continue
            lookahead = lines[idx + 1 : idx + 20]
            is_option_candidate, option_index = self._option_info(line.text)
            anchor = self._match_anchor(line.text, lookahead)
            anchor_number = self._last_anchor_number
            anchor_delim = self._last_anchor_delimiter
            anchor_found = anchor is not None

            if builder is not None and is_option_candidate:
                if self._should_treat_as_option(
                    builder,
                    line,
                    anchor_number,
                    anchor_delim,
                    option_index,
                    anchor_found,
                ):
                    builder.add_line(
                        line,
                        is_anchor_line=False,
                        is_option=True,
                        option_index=option_index,
                    )
                    continue

            if anchor is not None:
                if builder is not None and builder.lines:
                    segments.append(builder.to_segment())
                    next_index += 1
                display_number = anchor or str(next_index)
                builder = _ProblemBuilder(
                    index=next_index,
                    display_number=display_number,
                    anchor_pattern=self._last_anchor_name,
                )
                if self._pending_year_marker is not None:
                    builder.metadata.setdefault("exam_year", self._pending_year_marker)
                    self._pending_year_marker = None
                builder.add_line(line, is_anchor_line=True)
                continue

            if builder is not None:
                builder.add_line(
                    line,
                    is_option=is_option_candidate,
                    option_index=option_index,
                    append_last_option=self._is_option_continuation_text(line.text),
                )

        if builder is not None and builder.lines:
            segments.append(builder.to_segment())

        return self._refine_segments(segments)

    def _match_anchor(self, text: str, lookahead: Sequence[TextLine]) -> Optional[str]:
        self._last_anchor_name = "unknown"
        self._last_anchor_delimiter = None
        self._last_anchor_number = None
        for pattern in self.anchor_patterns:
            match = pattern.regex.match(text)
            if match:
                if pattern.name == "numeric_period" and not self._looks_like_question(text):
                    if not any(self._looks_like_question(candidate.text) for candidate in lookahead):
                        continue
                self._last_anchor_name = pattern.name
                matched_text = match.group(0)
                if ")" in matched_text:
                    self._last_anchor_delimiter = ")"
                elif "." in matched_text:
                    self._last_anchor_delimiter = "."
                else:
                    self._last_anchor_delimiter = None
                number = match.groupdict().get("num")
                if number:
                    try:
                        self._last_anchor_number = int(number)
                    except ValueError:
                        self._last_anchor_number = None
                    return number
                digits = re.findall(r"\d+", text)
                if digits:
                    try:
                        self._last_anchor_number = int(digits[0])
                    except ValueError:
                        self._last_anchor_number = None
                    return digits[0]
                return ""
        return None

    # ------------------------------------------------------------------
    # Option heuristics
    # ------------------------------------------------------------------
    def _looks_like_question(self, text: str) -> bool:
        lowered = text.lower()
        if "?" in text:
            return True
        question_cues = (
            "문항",
            "설명",
            "옳",
            "다음",
            "아닌",
            "틀린",
            "which",
            "what",
            "following",
            "고르시오",
            "선택",
            "어느",
        )
        return any(cue in lowered for cue in question_cues)

    def _is_year_marker(self, text: str) -> bool:
        return bool(self._year_pattern.match(text))

    def _is_author_line(self, text: str) -> bool:
        return bool(self._author_pattern.match(text))

    def _is_option_continuation_text(self, text: str) -> bool:
        stripped = text.strip()
        if not stripped:
            return False
        first_char = stripped[0]
        if first_char.isdigit():
            return False
        if first_char in self._circled_digit_map:
            return False
        if re.match(r"^[A-F][).]", stripped, re.IGNORECASE):
            return False
        if self._looks_like_question(stripped):
            return False
        if self._is_year_marker(stripped):
            return False
        if self._is_author_line(stripped):
            return False
        return True

    def _option_info(self, text: str) -> Tuple[bool, Optional[int]]:
        stripped = text.strip()
        if not stripped:
            return False, None

        first_char = stripped[0]
        if first_char in self._circled_digit_map:
            return True, self._circled_digit_map[first_char]

        numeric_match = re.match(r"^\s*\(?(\d{1,2})\)?([).])(?:\s+|$)", stripped)
        if numeric_match:
            try:
                return True, int(numeric_match.group(1))
            except ValueError:
                return True, None

        alpha_match = re.match(r"^\s*([A-F])([).])(?:\s+|$)", stripped, re.IGNORECASE)
        if alpha_match:
            return True, ord(alpha_match.group(1).upper()) - ord("A") + 1

        for pattern in self.option_patterns:
            if pattern.match(text):
                return True, None

        return False, None

    def _should_treat_as_option(
        self,
        builder: _ProblemBuilder,
        line: TextLine,
        anchor_number: Optional[int],
        anchor_delim: Optional[str],
        option_index: Optional[int],
        anchor_found: bool,
    ) -> bool:
        if not builder.lines:
            return False
        if "?" in line.text:
            return False
        last_line = builder.lines[-1]
        if line.page_index != last_line.page_index:
            return False
        if anchor_found:
            if anchor_delim != ")":
                return False
            if anchor_number is None:
                return True

        base_number = self._safe_int(builder.display_number)
        if base_number is None:
            base_number = 999

        if option_index is not None:
            if option_index <= max(6, builder.max_option_index + 1):
                if anchor_found:
                    if option_index <= base_number or base_number >= 10:
                        return True
                else:
                    if option_index <= builder.max_option_index + 1 or option_index <= 5:
                        return True
            if builder.max_option_index and option_index <= builder.max_option_index + 1:
                return True
            return option_index <= 5 and base_number >= 10

        if anchor_found and anchor_number is not None:
            return anchor_number <= 5 and base_number >= 10

        return False

    def _safe_int(self, value: str) -> Optional[int]:
        try:
            return int(re.findall(r"\d+", value)[0])
        except (IndexError, ValueError):
            return None

    def _refine_segments(self, segments: Sequence[ProblemSegment]) -> List[ProblemSegment]:
        refined: List[ProblemSegment] = []
        for segment in segments:
            if refined and self._segment_looks_like_option(segment):
                merged = self._merge_option_segment(refined[-1], segment)
                refined[-1] = merged
            else:
                refined.append(segment)

        normalized: List[ProblemSegment] = []
        for idx, segment in enumerate(refined, start=1):
            normalized.append(
                ProblemSegment(
                    index=idx,
                    display_number=segment.display_number,
                    text=segment.text,
                    options=list(segment.options),
                    page_spans={k: list(v) for k, v in segment.page_spans.items()},
                    anchor_pattern=segment.anchor_pattern,
                    metadata=dict(segment.metadata),
                )
            )
        return normalized

    def _segment_looks_like_option(self, segment: ProblemSegment) -> bool:
        if segment.anchor_pattern != "unknown":
            return False
        lines = [line.strip() for line in segment.text.splitlines() if line.strip()]
        if not lines:
            return False
        first_line = lines[0]
        if "?" in segment.text:
            return False
        is_option, option_index = self._option_info(first_line)
        if not is_option:
            return False
        if option_index is not None and option_index > 20:
            return False
        return True

    def _merge_option_segment(
        self,
        base: ProblemSegment,
        addition: ProblemSegment,
    ) -> ProblemSegment:
        option_blocks = self._extract_option_blocks(addition.text)
        if not option_blocks:
            option_blocks = [addition.text.strip()]

        merged_options = list(base.options)
        merged_options.extend(option_blocks)

        merged_text = base.text
        if addition.text.strip():
            merged_text = f"{base.text}\n{addition.text}"

        merged_page_spans: Dict[int, List[RectTuple]] = {
            page: list(rects) for page, rects in base.page_spans.items()
        }
        for page_index, rects in addition.page_spans.items():
            merged_page_spans.setdefault(page_index, []).extend(rects)

        return ProblemSegment(
            index=base.index,
            display_number=base.display_number,
            text=merged_text,
            options=merged_options,
            page_spans=merged_page_spans,
            anchor_pattern=base.anchor_pattern,
            metadata=dict(base.metadata),
        )

    def _extract_option_blocks(self, text: str) -> List[str]:
        blocks: List[str] = []
        current: List[str] = []
        for raw_line in text.splitlines():
            stripped = raw_line.strip()
            if not stripped:
                continue
            is_option, _ = self._option_info(stripped)
            if is_option:
                if current:
                    blocks.append(" ".join(current))
                    current = []
                current.append(stripped)
            else:
                if current:
                    current.append(stripped)
                else:
                    current.append(stripped)
        if current:
            blocks.append(" ".join(current))
        return blocks

    # ------------------------------------------------------------------
    # Output helpers
    # ------------------------------------------------------------------
    def _write_annotated_pdf(
        self,
        source_pdf: Path,
        target_pdf: Path,
        segments: Sequence[ProblemSegment],
    ) -> None:
        doc = fitz.open(source_pdf)
        try:
            color_cycle = itertools.cycle(self.highlight_palette)
            for segment in segments:
                color = next(color_cycle)
                for page_index, rects in segment.page_spans.items():
                    if page_index >= len(doc):
                        continue
                    page = doc[page_index]
                    first_rect: Optional[RectTuple] = None
                    for rect in rects:
                        fitz_rect = fitz.Rect(rect)
                        annot = page.add_rect_annot(fitz_rect)
                        annot.set_colors(stroke=color)
                        annot.set_border(width=0.8)
                        annot.update()
                        if first_rect is None:
                            first_rect = rect
                    if first_rect is not None:
                        x0, y0, _, _ = first_rect
                        label_y = max(y0 - 8, 12)
                        page.insert_text(
                            (x0, label_y),
                            f"[Q{segment.index}] {segment.display_number}",
                            fontsize=8,
                            fontname="helv",
                            color=color,
                        )
            doc.save(target_pdf, garbage=4, deflate=True)
        finally:
            doc.close()

    def _write_metadata_json(self, target: Path, segments: Sequence[ProblemSegment]) -> None:
        payload = []
        for segment in segments:
            pages = [
                {"page_index": page_index, "rects": rects}
                for page_index, rects in segment.page_spans.items()
            ]
            payload.append(
                {
                    "index": segment.index,
                    "display_number": segment.display_number,
                    "anchor_pattern": segment.anchor_pattern,
                    "text": segment.text,
                    "options": segment.options,
                    "metadata": segment.metadata,
                    "pages": pages,
                }
            )
        target.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


__all__ = [
    "ProblemSnipper",
    "ProblemSegment",
    "ExtractionArtifacts",
]
